{{- if and .Values.ingress.enabled .Values.basicAuth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: cognitive-load-basic-auth
  labels:
    {{- include "cognitive-load-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth: {{ .Values.basicAuth.auth | quote }}
{{- end }}
