{{- if .Values.kserve.enabled }}
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Values.kserve.name }}
  labels:
    {{- include "cognitive-load-monitor.labels" . | nindent 4 }}
  annotations:
    autoscaling.knative.dev/min-scale: {{ .Values.kserve.minScale | quote }}
    autoscaling.knative.dev/max-scale: {{ .Values.kserve.maxScale | quote }}
spec:
  predictor:
    sklearn:
      protocolVersion: {{ .Values.kserve.predictor.sklearn.protocolVersion | quote }}
      storageUri: {{ .Values.kserve.storageUri | quote }}
      resources:
        {{- toYaml .Values.kserve.predictor.sklearn.resources | nindent 8 }}
{{- end }}
